# Generated by Django 3.2.5 on 2021-10-08 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rateepargne',
            fields=[
                ('num_account', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tva_rate', models.FloatField()),
                ('inf_rate', models.FloatField()),
                ('sup_rate', models.FloatField()),
                ('ircm_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratesepargne', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratecourant',
            fields=[
                ('num_account', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('com_rate', models.FloatField()),
                ('dec_rate', models.FloatField()),
                ('tva_rate', models.FloatField()),
                ('int1_rate', models.FloatField()),
                ('int2_rate', models.FloatField()),
                ('int3_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratescourant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_folder', models.TextField()),
                ('file_type', models.CharField(max_length=20)),
                ('period', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('period', 'file_type')},
            },
        ),
        migrations.CreateModel(
            name='ActiveFileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_users_files', to='filesupload.file')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'file', 'type')},
            },
        ),
    ]
