# Generated by Django 3.2.3 on 2021-06-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_agence', models.CharField(max_length=20)),
                ('date_comptable', models.DateField()),
                ('date_valeur', models.DateField()),
                ('num_compte', models.CharField(max_length=11)),
                ('intitule_compte', models.CharField(max_length=100)),
                ('libelle_operation', models.CharField(max_length=100)),
                ('code_operation', models.CharField(max_length=5)),
                ('sens', models.CharField(max_length=2)),
                ('montant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Arretes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_agence', models.CharField(max_length=20)),
                ('num_compte', models.CharField(max_length=11)),
                ('montant', models.IntegerField()),
                ('date_deb_arrete', models.DateTimeField()),
                ('date_fin_arrete', models.DateTimeField()),
                ('date_deb_autorisation', models.DateTimeField()),
                ('date_fin_autorisation', models.DateTimeField()),
            ],
            options={
                'unique_together': {('num_compte', 'date_deb_arrete', 'date_fin_arrete', 'date_deb_autorisation', 'date_fin_autorisation')},
            },
        ),
    ]
