# Generated by Django 3.2.3 on 2021-06-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='date_comptable',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historique',
            name='date_valeur',
            field=models.DateTimeField(),
        ),
    ]
