# Generated by Django 3.2.3 on 2021-07-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='type_account',
        ),
    ]
