# Generated by Django 3.2.3 on 2021-07-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='libelle_operation',
            field=models.CharField(default='Pas de libellé', max_length=100),
        ),
    ]
