# Generated by Django 3.2.5 on 2021-08-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('date_inf', 'date_sup', 'longueur', 'file_type')},
        ),
    ]
