# Generated by Django 3.2.5 on 2021-10-08 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filesupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statisticourant',
            fields=[
                ('num_account', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('simulation_total', models.IntegerField()),
                ('journal_total', models.IntegerField()),
                ('journal_int_1', models.IntegerField()),
                ('journal_int_2', models.IntegerField()),
                ('journal_int_3', models.IntegerField()),
                ('journal_com_dec', models.IntegerField()),
                ('journal_com_mvt', models.IntegerField()),
                ('journal_tva', models.IntegerField()),
                ('simulation_frais', models.IntegerField()),
                ('journal_frais', models.IntegerField()),
                ('simulation_int_1', models.IntegerField()),
                ('simulation_int_2', models.IntegerField()),
                ('simulation_int_3', models.IntegerField()),
                ('simulation_com_dec', models.IntegerField()),
                ('simulation_com_mvt', models.IntegerField()),
                ('simulation_tva', models.IntegerField()),
                ('type', models.CharField(max_length=40)),
                ('ecart', models.IntegerField()),
                ('date_deb', models.DateField()),
                ('date_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statscourant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date_deb', 'date_fin', 'num_account')},
            },
        ),
        migrations.CreateModel(
            name='Statisticepargne',
            fields=[
                ('num_account', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('simulation_total', models.IntegerField()),
                ('journal_total', models.IntegerField()),
                ('journal_int_inf', models.IntegerField()),
                ('journal_int_sup', models.IntegerField()),
                ('journal_ircm', models.IntegerField()),
                ('journal_tva', models.IntegerField()),
                ('simulation_frais', models.IntegerField()),
                ('type', models.CharField(max_length=40)),
                ('journal_frais', models.IntegerField()),
                ('simulation_int_inf', models.IntegerField()),
                ('simulation_int_sup', models.IntegerField()),
                ('simulation_ircm', models.IntegerField()),
                ('simulation_tva', models.IntegerField()),
                ('valeur_credit', models.IntegerField()),
                ('ecart', models.IntegerField()),
                ('date_deb', models.DateField()),
                ('date_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statsepargne', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date_deb', 'date_fin', 'num_account')},
            },
        ),
    ]
