# Generated by Django 3.2.5 on 2021-08-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesupload', '0002_alter_file_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=20),
        ),
    ]
