# Generated by Django 3.2.3 on 2021-06-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesupload', '0002_auto_20210617_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('num_compte', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('intitule_compte', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_operation', models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
