# Generated by Django 3.2.3 on 2021-07-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesupload', '0002_remove_compte_type_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='delta',
            name='type_account',
            field=models.CharField(default='Courant', max_length=10),
        ),
    ]
