# Generated by Django 3.2.3 on 2021-06-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesupload', '0003_compte_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='type_account',
            field=models.CharField(default='E', max_length=2),
        ),
    ]